apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-api

spec:

  replicas: 2

  selector:
    matchLabels:
      app: employee-api


  template:

    metadata:
      labels:
        app: employee-api


    spec:

      containers:

      - name: employee-api

        image: employeeacr.azurecr.io/employee-api:latest
        imagePullPolicy: Always

        ports:

        - containerPort: 5000